'use strict';
/**
 * LED-5369: end-to-end proof of the LED-5366 shim fail-closed guard, driven
 * from the SHIPPED generator (bin/delimit-setup.js run as a real CLI), not a
 * copy of the template text.
 *
 * Isolation: setup runs as a child process with HOME pointed at a temp dir,
 * cwd at a temp (non-git) project dir, and PATH containing ONLY a temp stub
 * dir. The stubs make python3 report a version and fail everything else, so
 * no venv/pip/network work happens; every other external command (curl, npm,
 * gh, claude, codex, git, delimit-cli) is simply absent. The only write the
 * setup code can make outside HOME is /etc/profile.d/delimit-shims.sh (and
 * only when that file is absent and writable); we remove it afterwards iff
 * this test created it.
 *
 * No test here is skipped on developer-home state: system candidates such as
 * /usr/bin/claude are rewritten to temp paths in the EXECUTED copy of each
 * shim, and the rewrite is asserted.
 */
const { describe, it, before, after } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const SETUP = path.join(__dirname, '..', 'bin', 'delimit-setup.js');
const PROFILE_D = '/etc/profile.d/delimit-shims.sh';
const TOOLS = ['claude', 'gemini'];

let root, home, project, stubBin;
let profileDExistedBefore;

function writeExec(file, body) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body);
    fs.chmodSync(file, 0o755);
}

function runSetup() {
    const r = spawnSync(process.execPath, [SETUP], {
        cwd: project,
        env: {
            HOME: home,
            PATH: stubBin,
            CI: '1',
            DELIMIT_NON_INTERACTIVE: '1',
            DELIMIT_SETUP_UPDATED: '1', // skip the `npm view` self-update probe
            GIT_CEILING_DIRECTORIES: root,
        },
        encoding: 'utf-8',
        timeout: 120000,
    });
    assert.strictEqual(r.status, 0, `setup exited ${r.status}\nstdout:\n${r.stdout}\nstderr:\n${r.stderr}`);
    return r;
}

// Render the executed copy of a generated shim with system candidate dirs
// redirected into the sandbox. Returns the path of the rewritten copy.
function sandboxedShim(tool) {
    const generated = fs.readFileSync(path.join(home, '.delimit', 'shims', tool), 'utf-8');
    const sysLocal = path.join(root, 'sys', 'usr-local-bin') + '/';
    const sysUsr = path.join(root, 'sys', 'usr-bin') + '/';
    const localHits = generated.split('/usr/local/bin/').length - 1;
    const usrHits = generated.split('/usr/bin/').length - 1;
    const rewritten = generated.split('/usr/local/bin/').join(sysLocal).split('/usr/bin/').join(sysUsr);
    assert.ok(localHits > 0 && usrHits > 0, `${tool}: expected system candidates to rewrite (usr/local=${localHits}, usr=${usrHits})`);
    assert.ok(!rewritten.includes('/usr/bin/') && !rewritten.includes('/usr/local/bin/'),
        `${tool}: rewritten shim still references a real system candidate dir`);
    const out = path.join(root, 'exec-shims', tool);
    writeExec(out, rewritten);
    return out;
}

function runShimPiped(shim) {
    // spawnSync with default stdio => stdout is a pipe (non-tty).
    return spawnSync(shim, ['--print', 'hi'], {
        env: { HOME: home, PATH: '/usr/bin:/bin' },
        timeout: 20000,
    });
}

describe('LED-5369: shims generated by real setup fail closed on piped stdout', () => {
    before(() => {
        profileDExistedBefore = fs.existsSync(PROFILE_D);
        root = fs.mkdtempSync(path.join(os.tmpdir(), 'delimit-led5369-'));
        home = path.join(root, 'home');
        project = path.join(root, 'project');
        stubBin = path.join(root, 'stub-bin');
        fs.mkdirSync(home, { recursive: true });
        fs.mkdirSync(project, { recursive: true });
        const py = '#!/bin/sh\nif [ "$1" = "--version" ]; then echo "Python 3.12.0"; exit 0; fi\nexit 1\n';
        writeExec(path.join(stubBin, 'python3'), py);
        writeExec(path.join(stubBin, 'python'), py);
        runSetup(); // fresh install
    });

    after(() => {
        if (!profileDExistedBefore && fs.existsSync(PROFILE_D)) {
            try { fs.unlinkSync(PROFILE_D); } catch {}
        }
        try { fs.rmSync(root, { recursive: true, force: true }); } catch {}
    });

    it('fresh install into an isolated HOME writes the claude and gemini shims', () => {
        for (const tool of TOOLS) {
            const shim = path.join(home, '.delimit', 'shims', tool);
            assert.ok(fs.existsSync(shim), `${tool} shim not generated`);
            assert.ok(fs.statSync(shim).mode & 0o111, `${tool} shim not executable`);
            assert.match(fs.readFileSync(shim, 'utf-8'), /delimit-shim: no .* binary found/);
        }
    });

    for (const tool of TOOLS) {
        it(`${tool}: every candidate absent -> empty stdout, exit 127, diagnostic on stderr`, () => {
            const shim = sandboxedShim(tool);
            const r = runShimPiped(shim);
            assert.strictEqual(r.stdout.length, 0, `stdout not empty: ${JSON.stringify(r.stdout.toString())}`);
            assert.strictEqual(r.status, 127);
            assert.match(r.stderr.toString(), /delimit-shim/);
        });

        it(`${tool}: fake executable at a candidate -> exec'd, stdout byte-for-byte, exit 0`, () => {
            const shim = sandboxedShim(tool);
            const fake = path.join(home, '.local', 'bin', tool);
            const sentinel = Buffer.from(`SENTINEL-${tool}\n\x01\xfe tail`, 'latin1');
            writeExec(fake, `#!/bin/sh\nprintf '%b' '${Array.from(sentinel).map((b) => '\\0' + b.toString(8)).join('')}'\nexit 0\n`);
            try {
                const r = runShimPiped(shim);
                assert.strictEqual(r.status, 0, `exit ${r.status}; stderr ${r.stderr}`);
                assert.ok(Buffer.compare(r.stdout, sentinel) === 0,
                    `stdout mismatch: ${r.stdout.toString('hex')} vs ${sentinel.toString('hex')}`);
            } finally {
                fs.rmSync(fake, { force: true });
            }
        });

        it(`${tool}: churn -- candidate present then removed between runs fails closed`, () => {
            const shim = sandboxedShim(tool);
            const fake = path.join(root, 'sys', 'usr-bin', tool); // rewritten /usr/bin/<tool>
            writeExec(fake, `#!/bin/sh\necho CHURN-OK-${tool}\n`);
            const first = runShimPiped(shim);
            assert.strictEqual(first.status, 0);
            assert.strictEqual(first.stdout.toString(), `CHURN-OK-${tool}\n`);
            fs.rmSync(fake);
            const second = runShimPiped(shim);
            assert.strictEqual(second.stdout.length, 0, `stdout after removal: ${JSON.stringify(second.stdout.toString())}`);
            assert.strictEqual(second.status, 127);
            assert.match(second.stderr.toString(), /delimit-shim/);
        });

        it(`${tool}: guard is inside the non-tty if/fi block; interactive banner still follows`, () => {
            const lines = fs.readFileSync(path.join(home, '.delimit', 'shims', tool), 'utf-8').split('\n');
            let depth = 0, blockStart = -1, blockEnd = -1, guardLine = -1, guardDepth = -1, guardExit = -1;
            for (let i = 0; i < lines.length; i++) {
                const t = lines[i].trim();
                if (t.startsWith('#')) continue;
                // shell `if ...; then` only (the embedded awk program has C-style `if (`)
                const opens = /^if\s.*;\s*then\b/.test(t) ? 1 : 0;
                const closes = /(^|;\s*)fi(\s|\)|$)/.test(t) ? 1 : 0;
                if (opens && depth === 0 && t.includes('[ ! -t 1 ]')) blockStart = i;
                if (t.startsWith('echo "delimit-shim:')) { guardLine = i; guardDepth = depth; }
                if (guardLine >= 0 && guardExit < 0 && i > guardLine && t === 'exit 127') guardExit = i;
                depth += opens - closes;
                assert.ok(depth >= 0, `if/fi depth went negative at line ${i + 1}`);
                if (blockStart >= 0 && blockEnd < 0 && depth === 0 && i > blockStart) blockEnd = i;
            }
            assert.strictEqual(depth, 0, 'unbalanced if/fi in generated shim');
            assert.ok(blockStart >= 0 && blockEnd > blockStart, 'non-tty block not found');
            assert.ok(guardLine > blockStart && guardLine < blockEnd && guardDepth === 1,
                `guard (line ${guardLine + 1}, depth ${guardDepth}) not directly inside non-tty block ${blockStart + 1}-${blockEnd + 1}`);
            assert.ok(guardExit > guardLine && guardExit < blockEnd, 'exit 127 after guard is not inside the block');
            const banner = lines.findIndex((l, i) => i > blockEnd && l.includes('GOVERNANCE ACTIVE'));
            assert.ok(banner > blockEnd, 'interactive banner section missing after the non-tty block');
        });
    }

    it('upgrade over an existing install regenerates shims and preserves user files setup promises to keep', () => {
        // User customizations setup documents it preserves:
        //  - ~/CLAUDE.md content outside the delimit markers (upsertDelimitSection)
        //  - ~/.claude/settings.json existing keys (permissions merged, not replaced)
        //  - ~/.gemini/settings.json general.defaultApprovalMode ("never clobber on upgrade")
        //  - ~/.claude/agents/<name>.md (only written when absent)
        //  - shell rc: PATH line appended once, user content kept
        const claudeMd = path.join(home, 'CLAUDE.md');
        fs.writeFileSync(claudeMd, '# my own rules\nkeep me\n\n' + fs.readFileSync(claudeMd, 'utf-8'));
        // (A fresh install cannot create settings.json -- setup writes it
        // before ~/.claude exists -- so the user's own file is seeded here.)
        const settingsPath = path.join(home, '.claude', 'settings.json');
        fs.writeFileSync(settingsPath, JSON.stringify({ permissions: { allow: ['Bash(ls:*)'] }, theme: 'user-dark' }, null, 2));
        const geminiSettings = path.join(home, '.gemini', 'settings.json');
        fs.mkdirSync(path.dirname(geminiSettings), { recursive: true });
        fs.writeFileSync(geminiSettings, JSON.stringify({ general: { defaultApprovalMode: 'default' }, userKey: 1 }, null, 2));
        const agent = path.join(home, '.claude', 'agents', 'lint.md');
        fs.writeFileSync(agent, 'user-edited agent\n');
        const bashrc = path.join(home, '.bashrc');
        fs.appendFileSync(bashrc, 'alias ll="ls -l"\n');
        // Stale shim from an older release must be replaced by the upgrade.
        fs.writeFileSync(path.join(home, '.delimit', 'shims', 'claude'), '#!/bin/sh\necho stale\n');

        runSetup();

        const md = fs.readFileSync(claudeMd, 'utf-8');
        assert.ok(md.startsWith('# my own rules\nkeep me\n'), 'CLAUDE.md user content lost');
        const s = JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
        assert.strictEqual(s.theme, 'user-dark');
        assert.ok(s.permissions.allow.includes('Bash(ls:*)'));
        assert.ok(s.permissions.allow.includes('mcp__delimit__*'));
        const g = JSON.parse(fs.readFileSync(geminiSettings, 'utf-8'));
        assert.strictEqual(g.general.defaultApprovalMode, 'default');
        assert.strictEqual(g.userKey, 1);
        assert.strictEqual(fs.readFileSync(agent, 'utf-8'), 'user-edited agent\n');
        const rc = fs.readFileSync(bashrc, 'utf-8');
        assert.ok(rc.includes('alias ll="ls -l"'));
        assert.strictEqual(rc.split('.delimit/shims').length - 1, 1, 'PATH line duplicated on upgrade');
        for (const tool of TOOLS) {
            assert.match(fs.readFileSync(path.join(home, '.delimit', 'shims', tool), 'utf-8'), /delimit-shim: no .* binary found/,
                `${tool} shim not regenerated on upgrade`);
        }
    });
});
