# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from typing import Any, Dict, List, Optional
import json
import logging
import os
import shutil
import time
import urllib.error
import urllib.request

DELIBERATION_DIR = Path.home() / '.delimit' / 'deliberations'
MODELS_CONFIG = Path.home() / '.delimit' / 'models.json'
DEFAULT_MODELS = {'grok': {'name': 'Grok', 'api_url': 'https://api.x.ai/v1/chat/completions', 'model': 'grok-4-0709', 'env_key': 'XAI_API_KEY', 'enabled': False}, 'gemini': {'name': 'Gemini', 'api_url': 'https://us-central1-aiplatform.googleapis.com/v1/projects/{project}/locations/us-central1/publishers/google/models/gemini-2.5-flash:generateContent', 'model': 'gemini-2.5-flash', 'env_key': 'GOOGLE_APPLICATION_CREDENTIALS', 'enabled': False, 'format': 'vertex_ai', 'prefer_cli': True, 'cli_command': 'gemini'}, 'openai': {'name': 'OpenAI', 'api_url': 'https://api.openai.com/v1/chat/completions', 'model': 'gpt-4o', 'env_key': 'OPENAI_API_KEY', 'enabled': False, 'prefer_cli': True}, 'anthropic': {'name': 'Claude', 'api_url': 'https://api.anthropic.com/v1/messages', 'model': 'claude-sonnet-4-5-20250514', 'env_key': 'ANTHROPIC_API_KEY', 'enabled': False, 'format': 'anthropic', 'prefer_cli': True, 'cli_command': 'claude'}}
def get_models_config() -> Dict[str, Any]:
    ...

def configure_models() -> Dict[str, Any]:
    ...

def _call_cli(prompt: str, system_prompt: str, cli_path: str, cli_command: str) -> str:
    ...

def _call_model(model_id: str, config: Dict, prompt: str, system_prompt: str) -> str:
    ...

def deliberate(question: str, context: str, max_rounds: int, mode: str, require_unanimous: bool, save_path: Optional[str]) -> Dict[str, Any]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import json
import logging
import os
import shutil
import time
import urllib
import urllib.request
import urllib.error
import pathlib
import typing
import subprocess
import google
import google.auth
import google.auth.transport
import google.auth.transport.requests