# This file was generated by Nuitka

# Stubs included by default
import time
import json
import os
from pathlib import Path
import hashlib

PRO_TOOLS = frozenset({'delimit_agent_complete', 'delimit_agent_dispatch', 'delimit_agent_handoff', 'delimit_agent_status', 'delimit_cost_alert', 'delimit_cost_analyze', 'delimit_cost_optimize', 'delimit_deliberate', 'delimit_deploy_build', 'delimit_deploy_npm', 'delimit_deploy_plan', 'delimit_deploy_publish', 'delimit_deploy_rollback', 'delimit_deploy_site', 'delimit_deploy_status', 'delimit_deploy_verify', 'delimit_evidence_collect', 'delimit_evidence_verify', 'delimit_executor', 'delimit_gov_evaluate', 'delimit_gov_policy', 'delimit_gov_run', 'delimit_gov_verify', 'delimit_memory_search', 'delimit_models', 'delimit_notify', 'delimit_obs_logs', 'delimit_obs_metrics', 'delimit_obs_status', 'delimit_os_gates', 'delimit_os_plan', 'delimit_os_status', 'delimit_release_plan', 'delimit_release_status', 'delimit_release_sync', 'delimit_screen_record', 'delimit_screenshot', 'delimit_social_generate', 'delimit_social_history', 'delimit_social_post', 'delimit_vault_health', 'delimit_vault_search', 'delimit_vault_snapshot'})
def needs_revalidation(data: dict) -> bool:
    ...
def revalidate_license(data: dict) -> dict:
    ...
def is_license_valid(data: dict) -> bool:
    ...
def _write_license(data: dict) -> None:
    ...
def _call_lemon_squeezy(data: dict) -> bool | None:
    ...
def load_license() -> dict:
    ...
def check_premium() -> bool:
    ...
def gate_tool(tool_name: str) -> dict | None:
    ...
def activate(key: str) -> dict:
    ...
def _revalidate(data: dict) -> dict:
    ...
def _get_monthly_usage(tool_name: str) -> int:
    ...
def _increment_usage(tool_name: str) -> int:
    ...

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import hashlib
import json
import os
import time
import pathlib
import urllib
import urllib.request
import re